#server:
#  port: 8083
#
#person:
#  name: "张三"
#  age: 27
#  boss: false
#  birth: 2020/02/10
##  map: {k1: v1,k2: 12,k3: abc}
#  map:
#    k1: v1
#    k2: 12
#    k3: abc
##  list:
##    - 王五
##    - 李四
##    - 赵六
#  list: [王五, 李四, 赵六]
#  dog:
#    name: dou
#    age: 4