# 使用说明 V4.3.1
# 1. PowerJob 根目录执行：docker-compose up
# 2. 静静等待服务启动。

version: '3'
services:
  powerjob-mysql:
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: No1Bug2Please3!
    restart: always
    container_name: powerjob-mysql
    image: powerjob/powerjob-mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - ./powerjob-data/powerjob-mysql:/var/lib/mysql
    command: --lower_case_table_names=1

  powerjob-server:
    container_name: powerjob-server
    image: powerjob/powerjob-server:latest
    restart: always
    depends_on:
      - powerjob-mysql
    environment:
      JVMOPTIONS: "-Xmx512m"
      PARAMS: "--oms.mongodb.enable=false --spring.datasource.core.jdbc-url=jdbc:mysql://powerjob-mysql:3306/powerjob-daily?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai"
    ports:
      - "7700:7700"
      - "10086:10086"
      - "10010:10010"
    volumes:
      - ./powerjob-data/powerjob-server:/root/powerjob/server/

  powerjob-worker-samples:
    container_name: powerjob-worker-samples
    image: powerjob/powerjob-worker-samples:latest
    restart: always
    depends_on:
      - powerjob-mysql
      - powerjob-server
#    environment:
#      PARAMS: "--powerjob.worker.server-address=powerjob-server:7700"
    ports:
      - "8081:8081"
      - "27777:27777"
    volumes:
      - ./powerjob-data/powerjob-worker-samples:/root/powerjob/worker
      - ./others/script/wait-for-it.sh:/wait-for-it.sh
    entrypoint:
      - "sh"
      - "-c"
      - "chmod +x wait-for-it.sh && ./wait-for-it.sh powerjob-server:7700 --strict -- java -Xmx512m -jar /powerjob-worker-samples.jar --powerjob.worker.server-address=powerjob-server:7700"
